# DB ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3316/ebsoft
    username: ebsoft
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# ? ??? ??
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

# Hibernate ?? ?? ??
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
