# DB ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3316/ebsoft
    username: ebsoft
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# ? ??? ??
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

logging:
  level:
    org.springframework.web : debug
    sql: error
    jdbc: off
    jdbc.sqlonly: off

spring.servlet.multipart:
  enabled: false